create table if not exists public.files (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  path text not null,
  mime_type text not null,
  size text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.files add column if not exists user_id uuid references auth.users (id) on delete set null;

create index if not exists files_user_id_idx on public.files (user_id);
create index if not exists files_created_at_idx on public.files (created_at desc);

alter table public.files enable row level security;
drop policy if exists "files_authenticated_all" on public.files;
create policy "files_authenticated_all" on public.files for all to authenticated using (true) with check (true);
